# Generated by Django 4.2.7 on 2023-11-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(error_messages='no file uploaded', upload_to='gallery/static/media'),
        ),
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, error_messages='someting wrong with the tags', to='photos.tag'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(error_messages='no title detected', max_length=40, unique=True),
        ),
    ]
